# Generated by Django 4.0.4 on 2022-05-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Categories'},
        ),
    ]
