# Generated by Django 4.0.4 on 2022-05-14 13:14

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='viewer',
        ),
        migrations.AddField(
            model_name='budget',
            name='viewers',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='budgets', to='budgets.category'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='expenses',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=2), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='budget',
            name='incomes',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=2), blank=True, null=True, size=None),
        ),
    ]
