# Generated by Django 4.0.4 on 2022-05-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_remove_budget_category_remove_budget_expenses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('category__name',)},
        ),
    ]
