# Generated by Django 4.0.4 on 2022-05-16 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0005_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
